---
baseurl: https://www.logiquants.ca/
languageCode: en-us
title: LogiQuants | Investment Research
theme: parsa-hugo
summaryLength: '10'
paginate: 6
googleAnalytics: ''
outputs:
  home:
  - HTML
  - RSS
  - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  address: Toronto, ON. Canada
  author: LogiQuants
  author_image: images/Precision.png
  bio: Strong quantitative skills provide a significant advantage when searching for
    the best investment opportunities. However, a common issue for those with quantitative
    expertise is their inability to think logically. That's where LogiQuants comes
    in. Cut through the noise with our high quality investment research. It makes
    sense!
  contact_form_action: "#"
  cookies:
    enable: true
    expire_days: 2
  copyright: Â©2022 Logiquants Ltd. | [Privacy Policy](https://www.logiquants.ca/privacy-policy/) | [Terms & Conditions](https://www.logiquants.ca/terms-and-conditions/)
  #originalcopyright: Copyright &copy; 2020 a theme by [themefisher.com](https://themefisher.com)
  description: This is meta description
  email: contact@logiquants.ca
  home: Home
  instafeed:
    access_token: IGQVJVNmZAiMkh2X21RR1lGWGJra2k2ZA0dCYy04SjNNemN3RzhZANEJmang0enV6ampFZAm5ReUY4OVd5TkhkQ21xRTNPdi1iNWphSjVHX1c3WnYwdjJBX290QXFyT3NMTUpsbkc4aUVsUEl2TFZAlV2tPeQZDZD
    enable: true
  layout: '1'
  logo: images/new_logo.png
  #mobile: "+90 000 333 22"
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  preloader: true
  search: true
  social:
  - icon: ti-facebook
    link: https://www.facebook.com/Logiquants
  - icon: ti-twitter-alt
    link: https://twitter.com/logiquants
  - icon: ti-linkedin
    link: https://www.linkedin.com/company/logiquants/
  - icon: ti-instagram
    link: https://www.instagram.com/logiquants/
  - icon: ti-youtube
    link: https://www.youtube.com/channel/UCF04jhZolYlenDcltKHvMVA
menu:
  main:
  - url: homepage/home-1/
    name: Free Content
    parent: Homepage
    weight: 1
  - url: homepage/home-2/
    name: Premium Research
    parent: Homepage
    weight: 2
  - url: contact/
    name: Contact
    weight: 3
  - url: about/
    name: About
    weight: 2
  - name: Homepage
    weight: 1
    hasChildren: true
